### ISSUE TITLE
[Hetzner Cloud] Make Windows Server builds possible

### ISSUE THREAD

**Issue by hc-github-team-packer** [hetznercloud/packer-plugin-hcloud#15]
_This issue was originally opened by @Rick-McClatchie in https://github.com/hashicorp/packer/issues/7980 and has been migrated to this repository. The original issue description is below._

---
It would be great if there was a way to build Windows Server images with packer in the Hetzner Cloud.
https://www.packer.io/intro/getting-started/build-image.html#a-windows-example

**Comment by nywilken** [comment]
Support for automatically provisioning Windows instance on Hetzner Cloud is not supported https://docs.hetzner.com/cloud/servers/windows-on-cloud

Marking this issue as resolved. If things should change in the future, please feel free to open a PR with the needed changes to support Windows builds and we will gladly review.

**Comment by JaneX8** [comment]
Seems to be possibly as of now. And I am excited because I do use Packer to built a Windows Server image and I do uae Hetzner for Linux things already but I have no solution yet for deploying my Windows images in the cloud and and already qaa searching for other suppliers. If possible on Hetzner it would be perfect.
